Added tons of documentation and cleaned up some code
replydev/Quboscanner pull request #40
Opened 2023-11-23 04:40 UTC by Swofty-Developments

2023-11-23 05:35 UTC, Swofty-Developments commented
PR changes Java version to 21 in order to remove the need for preview flags, this will mean that the Git actions will have to be updated accordingly.

2023-11-30 21:14 UTC, replydev requested changes
Hi and thanks a lot for your contribution. Just one thing and we are good to go.

2023-11-30 21:14 UTC, replydev commented on src/main/java/me/replydev/qubo/CLI.java
> +        return arguments.stream().anyMatch(arg -> arg.equals("-Dfile.encoding=UTF-8"));
Why? It should be slower.

2023-11-30 21:47 UTC, replydev approved these changes

2023-11-30 21:47 UTC, merged

2023-11-30 22:17 UTC, Swofty-Developments commented
Thanks